hd_map: "Town06_hy.osm"

global_planning:
  lanelet2_settings:
    TURNING_RADIUS: 5.6
    POSITION_TOLERANCE: 1
    YAW_TOLERANCE: 0.1

prediction:
  method: "loaded_waypoint_predictor"
  # method: "constant_velocity_predictor"

local_planning:
  local_planning_frequency: 10
  lattice_settings:
    MAX_T: 5.0            # max prediction time [s]
    MIN_T: 5.0            # min prediction time [s]
    D_T: 1                 # prediction timestep length (s)
    dt: 0.1              # sample time

    d_r: 3.5
    d_l: 3.5
    D_S: 3.5              # sample Frenet d
    
    MAX_SPEED: 20.0       # maximum speed [m/s]
    MIN_SPEED: 0.0        # minimum speed [m/s]
    TARGET_SPEED: 15    # target speed [m/s]
    D_V_S: 5            # target speed sampling length [m/s]
    SAFE_DISTANCE: 5.0    # safe distance to the front vehicle[m]
    LOOK_AHEAD_DISTANCE: 20.0 # look ahead distance [m]

    K_J: 0.1
    K_T: 0.5
    K_D: 5
    K_LAT: 0.1
    K_LON: 0.8
    K_D_DIFF: 1
    
    MAX_ACCEL: 5          # maximum acceleration [m/ss]
    MAX_CURVATURE: 1.0    # maximum curvature [1/m]

control:
  control_frequency: 20
  pid_settings:
    lateral:
      K_P: 3.0
      K_I: 0.0
      K_D: 0.2
      output_max: 1
      output_min: -1 
      dt: 0.05
    longitudinal:
      K_P: 2.0
      K_I: 0.0
      K_D: 0.1
      output_max: 1
      output_min: 0
      dt: 0.05
    look_ahead: 4

vehicle_info:
  length: 4.69
  width: 2.0  
  wheelbase: 2.87
  overhang_rear: 0.978
  overhang_front: 0.874

