hd_map: "Town06_hy.osm"

global_planning:
  lanelet2_settings:
    TURNING_RADIUS: 5.6
    GOAL_TORELANCE: 5

prediction:
  method: "loaded_waypoint_predictor"
  # method: "constant_velocity_predictor"

local_planning:
  local_planning_frequency: 10
  lattice_settings:
    MAX_SPEED: 13.88          # maximum speed [m/s]
    MAX_ACCEL: 5          # maximum acceleration [m/ss]
    MAX_CURVATURE: 100.0    # maximum curvature [1/m]
    d_r: 3.5
    d_l: 3.5
    D_S: 1.7              # sample Frenet d
    DT: 1                 # prediction timestep length (s)
    dt: 0.1              # sample time
    MAX_T: 5.0            # max prediction time [s]
    MIN_T: 5.0            # min prediction time [s]
    TARGET_SPEED: 8.33     # target speed [m/s]
    D_T_S: 1.38            # target speed sampling length [m/s]
    N_S_SAMPLE: 4         # sampling number of target speed
    K_J: 0.1
    K_T: 0.5
    K_D: 5
    K_LAT: 0.1
    K_LON: 0.8

control:
  control_frequency: 20
  pid_settings:
    lateral:
      K_P: 2.0
      K_I: 0.0
      K_D: 0.2
      output_max: 1
      output_min: -1 
      dt: 0.05
    longitudinal:
      K_P: 2.0
      K_I: 0.0
      K_D: 0.1
      output_max: 1
      output_min: 0
      dt: 0.05

vehicle_info:
  length: 4.69
  width: 2.0  
  wheelbase: 2.87
  overhang_rear: 0.978
  overhang_front: 0.874

